spring:
  datasource:
    url: jdbc:mysql://localhost:8889/library_2?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

jwt:
  secret: librarySecretKey
  expirationMs: 86400000

business:
  uploadsDir: /Users/jordan/OC_Projet10/uploads
  loanPeriod: 4

---
spring:
  profiles: 'test'
  datasource:
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE'
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

